name: 自动生成插件列表

on:
  issues:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.12.8
      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Update Data
        run: |
          python generator/main.py

      - name: Commit & Push
        uses: action-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          force-push: "true"
          commit-message: "chore: 插件列表自动更新"
          name: github-actions[bot]
          email: github-actions[bot]@noreply.github.com
